### ISSUE TITLE
Cant add song to the database

### ISSUE THREAD

**Issue by nrag3d** [follperson/follzam#1]
Hey i have following problem when adding a song to the db. seems like it is missing the assets.db_access_info module but i cant find a package where it belongs to.

`domi@ubuntu:~/follzam/shazam$ python freezam.py add /quell/TMS.mp3
Command line call to Follzam
Namespace(album=None, artist=None, dir=False, genre=None, subparser_name='add', target='/quell/TMS.mp3', title=None, year=None)
Adding songs to database
Traceback (most recent call last):
  File "freezam.py", line 276, in <module>
    add(args.target, args.title, args.artist, args.album, args.dir, args.genre, args.year)
  File "freezam.py", line 34, in add
    from follzam.database_management import DatabaseHandler
  File "/home/domi/follzam/shazam/follzam/database_management.py", line 1, in <module>
    import assets.db_access_info as credentials
ImportError: No module named assets.db_access_info
`

**Comment by follperson** [comment]
Right - this was developed using a PostgreSQL server which needed credentials which lived in that file. 
I meant to pivot to a lighter sql flavor but forgt.. in the latest master I implemented some kind ugly but simple fixes to use Sqlite3 instead. you will also need to initialize the database file using `python freezam.py init`
